name: Clojars deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      run: lein deps
    - name: Deploy to clojars
      env: 
         CLOJARS_USER: ${{ secret.CLOJARS_USER }}
         CLOJARS_PASS: ${{ secret.CLOJARS_PASS }}
      run: lein deploy clojars
