name: Clojars deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      run: lein deps
    - name: Deploy to clojars
      run: lein deploy clojars
