name: Clojars deploy

on:
  push:
    branches: [ main ]
    paths: 
      - 'src/*'
      - 'project.clj'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      run: lein deps
    - name: Deploy to clojars
      env: 
         CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
         CLOJARS_PASS: ${{ secrets.CLOJARS_PASS }}
      run: lein deploy clojars
