name: Release
on:
  push:
    branches: [*]
    paths: 
      - 'src/**'
      - 'project.clj'
      - '.github/workflows/release.yml'

    
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [amd64, macos]
        gu-binary: [gu, gu]

    runs-on: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate clj-holmes uberjar
        run: lein do deps, clean, uberjar

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        id: setup-graalvm
        with:
          graalvm-version: 21.3.0.java11

      - name: Install native-image component
        run: | 
          ${{ matrix.gu-binary }} install native-image

      - name: Generate clj-holmes native binarty
        run: lein native -H:Name=target/clj-holmes-${{ matrix.version }}

      - name: Retrieve version
        run: echo "TAG_NAME=v$(lein project-version)" >> $GITHUB_ENV

          #- name: Release
          #  uses: softprops/action-gh-release@v1
          #  with:
          #    tag_name: ${{ env.TAG_NAME }}
          #    files: ./target/clj-holmes
