on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate clj-holmes uberjar
        run: lein do deps, clean, uberjar

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        id: setup-graalvm
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - name: Install native-image component
        run: gu install native-image

      - name: Generate clj-holmes native binarty
        run: lein native
      
      - name: Retrieve version
        run: |
          echo ::set-env name=TAG_NAME::$(lein project-version)')
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${ env.TAG_NAME }
          files: ./target/clj-holmes
