name: Release
on:
  push:
    paths: 
      - 'src/**'
      - 'project.clj'
      - '.github/workflows/release.yml'

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest]
        gu-binary: [gu]
        include: 
          - os: ubuntu-latest
            native-image: native-image
            version: linux-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          lein: latest

      - name: Setup Graalvm
        uses: DeLaGuardo/setup-graalvm@master
        id: setup-graalvm
        with:
          graalvm-version: 21.3.0.java11

      - name: Install native-image component
        run: | 
          ${{ matrix.gu-binary }} install native-image

      - name: Download project dependencies
        run: lein deps

      - name: Clean target directory
        run: lein clean

      - name: Generate clj-holmes uberjar
        run: lein uberjar

      - name: Generate clj-holmes native binarty
        run: |
          lein native -H:Name=clj-holmes-${{ matrix.os }}

      - name: Retrieve version
        run: echo "TAG_NAME=v$(lein project-version)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: clj-holmes-${{ matrix.os }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rancorzinho:latest
