name: Clojure tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 'latest'

      - name: Run lint
        run: clojure -M:clojure-lsp format --dry
  
      - name: Run tests
        run: clojure -M:test

