name: Update VERSION.md file
on:
  push:
    branches: [ main ]
      - 'project.clj'

jobs:
  update-version-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          lein project-version > VERSION.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
